
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, :path => 'setup.sh'
  config.vm.hostname = 'vagrant-ubuntu-trusty-64'
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
