
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, :path => 'setup.sh'
  config.vm.hostname = 'vagrant-ubuntu'
  config.vm.network :forwarded_port, guest: 22, host: 2224, id: 'ssh'

  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
