# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = 'ubuntu/trusty64'
	config.vm.network :private_network, ip: '192.168.0.100'
	config.vm.hostname = 'master'
	config.vm.provision :shell, :path => 'setup.sh'
	
	config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
