# -*- mode: ruby -*-
# vi: set ft=ruby :


VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :master do |master|
    master.vm.box = 'ubuntu/trusty64'
    master.vm.network :private_network, ip: '192.168.1.100'
    master.vm.hostname = 'master'
    master.vm.provision :shell, :path => 'setup.sh'
  end
end
